# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-14 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dumper', '0002_auto_20180314_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tf4geenodebm',
            name='field_enodeb_sctpref',
            field=models.CharField(blank=True, db_column='field_enodeb_sctpRef', max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='tf4geenodebm',
            name='field_enodeb_upipaddressref',
            field=models.CharField(blank=True, db_column='field_enodeb_upIpAddressRef', max_length=191, null=True),
        ),
        migrations.AlterModelTable(
            name='tf4geenodebm',
            table=None,
        ),
    ]
