# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-14 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dumper', '0003_auto_20180314_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tf4geenodebm',
            name='field_enodeb_nnsfmode',
            field=models.CharField(blank=True, db_column='field_enodeb_nnsfMode', default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='tf4geenodebm',
            name='field_enodeb_stnnodes',
            field=models.CharField(blank=True, db_column='field_enodeb_stnNodes', default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='tf4geenodebm',
            name='field_enodeb_tcunodes',
            field=models.CharField(blank=True, db_column='field_enodeb_tcuNodes', default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='tf4geenodebm',
            name='field_enodeb_timephasemaxdeviation',
            field=models.CharField(blank=True, db_column='field_enodeb_timePhaseMaxDeviation', default='', max_length=45, null=True),
        ),
    ]
