# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-14 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dumper', '0005_auto_20180314_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tf4geenodebm',
            name='field_enodeb_tcunodes',
            field=models.CharField(db_column='field_enodeb_tcuNodes', default='', max_length=45),
        ),
    ]
