# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-23 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dumper', '0011_auto_20180323_0634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ENodeBFunction',
        ),
    ]
