# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-23 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dumper', '0013_enodebfunction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionControll',
            fields=[
                ('field_enodeb_id', models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='Station ID')),
                ('field_enodeb_resourceReservationForDifferentiation', models.CharField(blank=True, db_column='field_enodeb_resourceReservationForDifferentiation', default='', max_length=45, null=True)),
                ('field_enodeb_zzzTemp20', models.CharField(blank=True, db_column='field_enodeb_zzzTemp20', max_length=45, null=True)),
                ('field_enodeb_zzzTemp21', models.CharField(blank=True, db_column='field_enodeb_zzzTemp21', max_length=45, null=True)),
                ('field_enodeb_zzzTemporary7', models.CharField(blank=True, db_column='field_enodeb_zzzTemporary7', max_length=45, null=True)),
                ('field_enodeb_dlMbmsGbrRatio', models.CharField(blank=True, db_column='field_enodeb_dlMbmsGbrRatio', max_length=45, null=True)),
                ('field_enodeb_dlAdmOverloadThr', models.CharField(blank=True, db_column='field_enodeb_dlAdmOverloadThr', max_length=45, null=True)),
                ('field_enodeb_paArpOverride', models.CharField(blank=True, db_column='field_enodeb_paArpOverride', max_length=45, null=True)),
                ('field_enodeb_ulAdmDifferentiationThr', models.CharField(blank=True, db_column='field_enodeb_ulAdmDifferentiationThr', max_length=45, null=True)),
                ('field_enodeb_resourceReservationForPAState', models.CharField(blank=True, db_column='field_enodeb_resourceReservationForPAState', max_length=45, null=True)),
                ('field_enodeb_ulTransNwBandwidth', models.CharField(blank=True, db_column=' field_enodeb_ulTransNwBandwidth', max_length=45, null=True)),
                ('field_enodeb_nrOfPaConnReservationsPerCell', models.CharField(blank=True, db_column='field_enodeb_nrOfPaConnReservationsPerCell', max_length=45, null=True)),
                ('field_enodeb_zzTemp4', models.CharField(blank=True, db_column='field_enodeb_zzTemp4', max_length=45, null=True)),
                ('field_enodeb_zzzTemp5', models.CharField(blank=True, db_column='field_enodeb_zzzTemp5', max_length=45, null=True)),
                ('field_enodeb_zzzTemp2', models.CharField(blank=True, db_column='field_enodeb_zzzTemp2', max_length=45, null=True)),
                ('field_enodeb_zzzTemp3', models.CharField(blank=True, db_column='field_enodeb_zzzTemp3', max_length=45, null=True)),
                ('field_enodeb_arpBasedPreEmptionState', models.CharField(blank=True, db_column='field_enodeb_arpBasedPreEmptionState', max_length=45, null=True)),
                ('field_enodeb_zzzTemp10', models.CharField(blank=True, db_column='field_enodeb_zzzTemp10', max_length=45, null=True)),
                ('field_enodeb_zzzTemp1', models.CharField(blank=True, db_column='field_enodeb_zzzTemp1', max_length=45, null=True)),
                ('field_enodeb_zzzTemp11', models.CharField(blank=True, db_column='field_enodeb_zzzTemp11', max_length=45, null=True)),
                ('field_enodeb_zzzTemp12', models.CharField(blank=True, db_column='field_enodeb_zzzTemp12', max_length=45, null=True)),
                ('field_enodeb_dlTransNwBandwidth', models.CharField(blank=True, db_column='field_enodeb_dlTransNwBandwidth', max_length=45, null=True)),
                ('field_enodeb_ulAdmOverloadThr', models.CharField(blank=True, db_column='field_enodeb_ulAdmOverloadThr', max_length=45, null=True)),
                ('field_enodeb_zzzTemp8', models.CharField(blank=True, db_column='field_enodeb_zzzTemp8', max_length=45, null=True)),
                ('field_enodeb_zzzTemp9', models.CharField(blank=True, db_column='field_enodeb_zzzTemp9', max_length=45, null=True)),
                ('field_enodeb_zzzTemp6', models.CharField(blank=True, db_column='field_enodeb_zzzTemp6', max_length=45, null=True)),
                ('field_enodeb_zzzTemp7', models.CharField(blank=True, db_column='field_enodeb_zzzTemp7', max_length=45, null=True)),
                ('field_enodeb_admNrRbDifferentiationThr', models.CharField(blank=True, db_column='field_enodeb_admNrRbDifferentiationThr', max_length=45, null=True)),
                ('field_enodeb_zzzTemporary2', models.CharField(blank=True, db_column='field_enodeb_zzzTemporary2', max_length=45, null=True)),
                ('field_enodeb_zzzTemporary1', models.CharField(blank=True, db_column='field_enodeb_zzzTemporary1', max_length=45, null=True)),
                ('field_enodeb_admNrRrcDifferentiationThr', models.CharField(blank=True, db_column='field_enodeb_admNrRrcDifferentiationThr', max_length=45, null=True)),
                ('field_enodeb_zzzTemporary4', models.CharField(blank=True, db_column='field_enodeb_zzzTemporary4', max_length=45, null=True)),
                ('field_enodeb_zzzTemporary3', models.CharField(blank=True, db_column='field_enodeb_zzzTemporary3', max_length=45, null=True)),
                ('field_enodeb_zzzTemporary6', models.CharField(blank=True, db_column='field_enodeb_zzzTemporary6', max_length=45, null=True)),
                ('field_enodeb_zzzTemporary5', models.CharField(blank=True, db_column='field_enodeb_zzzTemporary5', max_length=45, null=True)),
                ('field_enodeb_zzzTemp14', models.CharField(blank=True, db_column='field_enodeb_zzzTemp14', max_length=45, null=True)),
                ('field_enodeb_zzzTemp13', models.CharField(blank=True, db_column='field_enodeb_zzzTemp13', max_length=45, null=True)),
                ('field_enodeb_zzzTemp16', models.CharField(blank=True, db_column='field_enodeb_zzzTemp16', max_length=45, null=True)),
                ('field_enodeb_admResourceMinQciPrio', models.CharField(blank=True, db_column='field_enodeb_admResourceMinQciPrio', max_length=45, null=True)),
                ('field_enodeb_zzzTemp15', models.CharField(blank=True, db_column='field_enodeb_zzzTemp15', max_length=45, null=True)),
                ('field_enodeb_zzzTemp18', models.CharField(blank=True, db_column='field_enodeb_zzzTemp18', max_length=45, null=True)),
                ('field_enodeb_zzzTemp17', models.CharField(blank=True, db_column='field_enodeb_zzzTemp17', max_length=45, null=True)),
                ('field_enodeb_nrOfRbReservationsPerPaConn', models.CharField(blank=True, db_column='field_enodeb_nrOfRbReservationsPerPaConn', max_length=45, null=True)),
                ('field_enodeb_dlAdmDifferentiationThr', models.CharField(blank=True, db_column='field_enodeb_dlAdmDifferentiationThr', max_length=45, null=True)),
                ('field_enodeb_zzzTemp19', models.CharField(blank=True, db_column='field_enodeb_zzzTemp19', max_length=45, null=True)),
                ('field_enodeb_zzzTemporary22', models.CharField(blank=True, db_column='field_enodeb_zzzTemporary22', max_length=45, null=True)),
                ('field_enodeb_zzzTemporary25', models.CharField(blank=True, db_column='field_enodeb_zzzTemporary25', max_length=45, null=True)),
                ('field_enodeb_zzzTemporary26', models.CharField(blank=True, db_column='field_enodeb_zzzTemporary26', max_length=45, null=True)),
                ('field_enodeb_zzzTemporary23', models.CharField(blank=True, db_column='field_enodeb_zzzTemporary23', max_length=45, null=True)),
                ('field_enodeb_zzzTemporary24', models.CharField(blank=True, db_column='field_enodeb_zzzTemporary24', max_length=45, null=True)),
                ('field_enodeb_lbAtoThresholdLevel2', models.CharField(blank=True, db_column='field_enodeb_lbAtoThresholdLevel2', max_length=45, null=True)),
                ('field_enodeb_lbAtoThresholdLevel1', models.CharField(blank=True, db_column='field_enodeb_lbAtoThresholdLevel1', max_length=45, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='enodebfunction',
            name='field_enodeb_zzztemporary54',
        ),
        migrations.AddField(
            model_name='enodebfunction',
            name='field_enodeb_zzzTemporary54',
            field=models.CharField(blank=True, db_column='field_enodeb_zzzTemporary54', max_length=45, null=True),
        ),
    ]
